servicenow_ticket_response_task:
  description: >
    Process ServiceNow ticket notifications fetched from Gmail (assumed to be available from a before_kickoff step, e.g., in 'output/fetched_emails.json'). The 'user_preference.txt' knowledge file contains ServiceNow instance details, SLA guidelines, and response templates.

    For each ServiceNow ticket email:
      1. **Identify Ticket Type**: Determine if it's an Incident (INC), Service Request (REQ), Change Request (CHG), or Problem (PRB) based on email subject and body.
      2. **Extract Key Information**:
         - Ticket number (e.g., INC0001234, REQ0005678)
         - Priority/Urgency level (e.g., P1, P2, High, Medium)
         - Affected user/requester name or email
         - Brief description of the issue or request
         - Current status if mentioned (e.g., New, In Progress, Pending)
      3. **Assess Response Requirements based on 'user_preference.txt'**:
         - Refer to 'Response Priority' and 'SLA EXPECTATIONS' sections in 'user_preference.txt'.
         - CRITICAL (e.g., P1/P2 incidents, system outages): Requires immediate acknowledgment.
         - HIGH (e.g., P3 incidents, change approvals): Requires prompt attention.
         - MEDIUM (e.g., Service requests): Standard processing.
         - LOW (e.g., General inquiries): Standard processing.
      4. **Generate Appropriate Response using 'user_preference.txt' templates**:
         - Utilize templates from 'Ticket Response Templates' section (e.g., Incident Acknowledgment, Request Fulfillment).
         - Acknowledge receipt within SLA timeframes.
         - Provide status updates or request additional information if needed.
         - Offer initial troubleshooting steps if applicable and defined.
         - Escalate if necessary, based on priority, complexity, and 'ESCALATION PROCEDURES' in 'user_preference.txt'.
      5. **Use Professional ServiceNow Communication Style**:
         - Ensure the ticket number is in the subject line of the reply.
         - Reference SLA commitments where appropriate.
         - Provide clear next steps for the user.
         - Use appropriate technical terminology.
         - Include relevant knowledge base article links if helpful (from 'Knowledge Base References' in 'user_preference.txt').

    IMPORTANT: - Only respond to legitimate ServiceNow ticket notifications that require action. - Skip emails that are purely informational and don't require a direct response from you (e.g., ServiceNow system maintenance notifications, training announcements, general ServiceNow community emails, automated reports not needing action). - Use the 'save_email_draft' tool for all generated responses. The subject should be "Re: [Original Subject]" and the recipient should be the original sender of the ticket email.

  expected_output: >
    A comprehensive JSON report detailing the ServiceNow tickets processed. Each entry in the report should include: - Original Email ID and Subject. - Extracted Ticket Number and Type (INC/REQ/CHG/PRB). - Assessed Priority. - Action Taken: (e.g., "Drafted Acknowledgment", "Drafted Information Request", "Skipped - Informational", "Marked for Escalation Review"). - Recipient of the draft. - Filename of the saved draft if one was created. - Brief summary of the response generated or reason for skipping. - Any identified escalation needs based on 'user_preference.txt'. The report should be saved to the specified output file.
  agent: response_generator
  output_file: output/servicenow_ticket_report.json
