response_task:
  description: >
    For each incoming ServiceNow ticket email:
      - Analyze the ticket content using your LLM capabilities.
      - If a reply is needed (e.g., the ticket requires clarification, status update, or technical input), draft a professional and relevant response.
      - If no reply is needed (e.g., informational, automated, or resolved tickets), skip responding.

    Use your knowledge of ServiceNow ticket workflows and best practices. Only reply when your LLM analysis determines a response is appropriate.

    Save all drafted replies as email drafts for review.
  expected_output: >
    A summary report listing each ticket email processed, indicating whether a reply draft was created or if no reply was needed. Include ticket ID, subject, recipient, and action taken.
  agent: response_generator
  output_file: output/response_report.json
